GITLAB_IMAGE: gitlab/gitlab-ce
GITLAB_IMAGE_TAG: 16.8.3-ce.0
GITLAB_DIRE_NAME: /var/services/gitlab

# Gitlab Domain
DOMAIN_ADDRESS: cicd.tlow.ir
GIT_SUB: gitlab
RIGISTRY_SUB: reg
PAGES_SUB: pages
GIT_DOMAIN: gitlab.cicd.tlow.ir

# GitLab image tag
GITLAB_IMAGE_TAG: 16.8.3-ce.0

# Gitlab root password
GITLAB_ROOT_PASSWORD: dev1234567

# SMTP Server Configuration
SMTP_USER: youremailaddreas
SMTP_PASS: xxx
SMTP_ADDRESS: smtp.gmail.com
SMTP_PORT: 587

# Minio information
MINIO_ACCESS_KEY: xxx
MINIO_SECRET_KEY: xxx
MINIO_ENDPOINT_URL: https://io.cicd.tlow.ir
MINIO_BACKUP_BUCKET_NAME: gitlab-backups
MINIO_REGISTRY_BUCKET_NAME: gitlab-registries
