
---
- name: copy compose file
  template:
    src: compose.yml.j2
    dest: "{{ ELK_PROMETHEUS_DIRE_NAME}}/compose.yml"

- name: copy env file
  template:
    src: env.j2
    dest: "{{ ELK_PROMETHEUS_DIRE_NAME}}/.env"

- name: copy blackbox file
  template:
    src: blackbox-exporter.yml.j2
    dest: "{{ PROMETHEUS_DIRE_NAME }}/blackbox/blackbox-exporter.yml"
 