---
- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
  tags: create_directories
  loop:
    - "{{ PROMETHEUS_DIRE_NAME }}/"
    - "{{ PROMETHEUS_DIRE_NAME }}/alertmanager"
    - "{{ PROMETHEUS_DIRE_NAME }}/blackbox"
    - "{{ PROMETHEUS_DIRE_NAME }}/grafana"
    - "{{ PROMETHEUS_DIRE_NAME }}/grafana/dashboards"
    - "{{ PROMETHEUS_DIRE_NAME }}/datasources"
    - "{{ PROMETHEUS_DIRE_NAME }}/prometheus"
    - "{{ PROMETHEUS_DIRE_NAME }}/prometheus/alert"
    - "{{ PROMETHEUS_DIRE_NAME }}/logstash/pipeline"
    - "{{ PROMETHEUS_DIRE_NAME }}/metricbeat"
    - "{{ PROMETHEUS_DIRE_NAME }}/packetbeat"
