---
- name: Create web_net network
  docker_network:
    name: web_net
    
- name: Create app_net network
  docker_network:
    name: app_net 

- name: Run `docker-compose up`
  tags: composeup
  docker_compose:
    project_src: "{{ PROMETHEUS_PROMETHEUS_DIRE_NAME}}"
    build: no
    files:
      - compose.yml
  register: output

- debug:
    var: output
