---
- hosts: rabbit
  become: true
  gather_facts: yes
  name: install and configure rabbit stack
  roles:
  # install and configure rabbit reverse proxyu
    - { role: rabbit, become: True, tags: rabbit_setup }