---
- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ REPO_DIRE_NAME }}"

- name: copy Docker Compose files
  template:
    src: docker-compose.yaml.j2
    dest: "{{ REPO_DIRE_NAME }}/docker-compose.yaml"

- name: Create web_net network
  docker_network:
    name: web_net
    
- name: Create app_net network
  docker_network:
    name: app_net 
    
- name: Run `docker-compose up` 
  docker_compose:
    project_src: "{{ REPO_DIRE_NAME }}"
    build: no
    files:
      - docker-compose.yaml
  register: output

- debug:
    var: output
 