
---
- name: copy compose file
  template:
    src: compose.yml.j2
    dest: "{{ rabbit_DIRE_NAME}}/compose.yml"

- name: copy env file
  template:
    src: env.j2
    dest: "{{ rabbit_DIRE_NAME}}/.env"

- name: copy config file
  template:
    src: rabbitmq.conf.j2
    dest: "{{ rabbit_DIRE_NAME}}/configfile/rabbitmq.conf"