---
- name: pull all image
  include: image-pull.yml
  tags: imagepull

- name: copy create directories 
  include: create-directories.yml
  tags: createdirs
  
- name: copy needed files
  include: copy-files.yml
  tags: copyfiles
  
- name: config and setup all service
  include: gitlab-setup.yml
  tags: composeup


# docker pull gitlab/gitlab-ce:16.8.3-ce.0
# docker pull gitlab/gitlab-ce:16.8.3-ce.0
# docker pull gitlab/gitlab-ce:16.8.3-ce.0
# docker pull gitlab/gitlab-ce:16.8.3-ce.0
# docker pull gitlab/gitlab-ce:16.8.3-ce.0
# docker pull gitlab/gitlab-ce:16.8.3-ce.0
# docker pull gitlab/gitlab-ce:16.8.3-ce.0
# docker pull gitlab/gitlab-ce:16.8.3-ce.0
